### ISSUE TITLE
Can't publish for .NET Core 3.1

### ISSUE THREAD

**Issue by wegylexy** [CommunityToolkit/Microsoft.Toolkit.Win32#327]
## Describe the bug
```
(_HandleFileConflictsForPublish target) ->
  ...\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: ...\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\build\..\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml, ...\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml.
```
## Steps to Reproduce
1. `msbuild /t:publish` or publish in Visual Studio

## Expected behavior
Publish successfully

## Environment

```
NuGet Package(s): 
Microsoft.Toolkit.UI.XamlHost
Package Version(s): 
no matter 6.0.0 up to 6.1.2
Project .NET Version:
.NET Core 3.1.18

Windows 10 Build Number:
Insider Build (build number: 21390)

Device form factor:
Desktop

Visual Studio 
2022 Preview (version: 3.1)

```

## Additional context
Didn't try to publish with .NET Framework 4.8 before because there were just a few files.

**Comment by wegylexy** [comment]
```
System.ArgumentException: Invalid input specification: Found entries 'D:\TimTim\.nuget\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml' and 'D:\TimTim\.nuget\microsoft.toolkit.win32.ui.xamlapplication\6.1.2\build\..\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.xml' with the same BundleRelativePath 'Microsoft.Toolkit.Win32.UI.XamlHost.xml'
   at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)
   at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
The 2 xml files want to be bundled at the same path.

**Comment by wegylexy** [comment]
I'm actually looking for 3D MapControl in WinUI 3 or .NET 6 unpackaged desktop app.

**Comment by wegylexy** [comment]
Is this repo still maintained?

**Comment by michalleptuch** [comment]
@wegylexy Try to add this code to your csproj
`<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>`

**Comment by wegylexy** [comment]
Never mind if Bing Maps 3D won't work with .NET 7.
